### ISSUE TITLE
Syslog and Eventlog sinks for promlog

### ISSUE THREAD

**Issue by Gouthamve** [prometheus/common#106]
The new go-kit based logger only prints to stderr. Should we add the syslog and eventlog sinks that are present in the previous logger?

@brian-brazil @grobie @fabxc

**Comment by brancz** [comment]
My personal opinion is that your environment should take care of this. There are infinite amounts of solutions that could be supported, but all of them can be used with little to no extra tooling around Prometheus.

**Comment by brian-brazil** [comment]
I agree with @brancz.

**Comment by grobie** [comment]
@mdlayher @cagedmantis I believe DigitalOcean relies heavily on syslog in the logging infrastructure. How do you deal with applications which only log to stdout? Anything which would make it impossible to use a wrapper to write the log stream to syslog instead?

@carlpett You added the EventLog back then for the wmi_exporter. I assume the wmi_exporter could just use implement its own logger for that? Do you run Prometheus on Windows as well? Do you see any issues writing to stdout only?

**Comment by mdlayher** [comment]
Pinging @taotetek about the logging question. I imagine we are able to just capture stdout but our internal structured logger has syslog support too, though I'd also rather have an external process be responsible for that.

**Comment by carlpett** [comment]
@grobie We could implement it ourselves, yes. 
We're not running the Prometheus server on Windows in my organisation, but I've heard that there are people elsewhere who do. Since there is no Windows Service support built in to Prometheus (there is an API that needs to be implemented in order to run as a service), anyone who does will need to have implemented some form of wrapper, and that wrapper should be able to handle output redirection. So I do not think that case is a problem.

**Comment by fabxc** [comment]
From what I could see, our syslog sink was best-effort at best. It comes with its own various config parameters and we made some effort to map log levels etc. to those – but I don't think that was necessarily the only sane way to do it.

**Comment by grobie** [comment]
Alright, let's not do this for now.

If someone comes up with critical reason why any of these sinks can only be sanely implemented here and not as a wrapper, please open this issue again and we can discuss.
