### ISSUE TITLE
How to pass a httprouter.Handle to a prometheus http.HandleFunc

### ISSUE THREAD

**Issue by wzf1943** [prometheus/common#189]
Cannot pass prometheus midware into httprouter endpoint definitions.

I'm trying to add a prometheus midware into our endpoint implementation. But our endpoint are using a third party mux package called httprouter. Then when I tried to add this midware into existing code base, I cannot find a good way to integrate both together.

```golang

router := httprouter.New()
router.GET("/hello", r.Hello)

func (r configuration) Hello(w http.ResponseWriter, req *http.Request, ps httprouter.Params)

func InstrumentHandlerFunc(name string, handler http.HandlerFunc) http.HandlerFunc {
    counter := prometheus.NewCounterVec(
		do something...
	)

	duration := prometheus.NewHistogramVec(
		do something...
	)
	return promhttp.InstrumentHandlerDuration(duration,
		promhttp.InstrumentHandlerCounter(counter, handler))
}

```

```go
Below is what I want to do

func InstrumentHandlerFunc(name string, handler httprouter.Handle) httprouter.Handel {

}

router.Get("/hello", InstrumentHandlerFunc("/hello", r.Hello))

```

**Comment by brian-brazil** [comment]
It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
