### ISSUE TITLE
text format parsing error in line 3: second TYPE line for metric name \"light_8618\", or TYPE reported after samples"

### ISSUE THREAD

**Issue by 277631272** [prometheus/common#265]
Hi.
I'm using current github.com/prometheus/common v0.14.0 build of exporter

error message:
text format parsing error in line 3: second TYPE line for metric name \"light_8618\", or TYPE reported after samples"

  
  1 # TYPE light_8618 counter                                                                           
  2 light_8618{set_id="0",classify_id="1068578"} 19264182.000000                                        
  3 # TYPE light_8618 counter                                                                           
  4 light_8618 18914014.000000

**Comment by brian-brazil** [comment]
The error is correct, this is invalid exposition.

It makes more sense to ask questions like this on the [prometheus-users mailing list](https://groups.google.com/forum/#!forum/prometheus-users) rather than in a GitHub issue. On the mailing list, more people are available to potentially respond to your question, and the whole community can benefit from the answers provided.
