### ISSUE TITLE
Remove cyclic dependency between `prometheus/common` and `prometheus/client_golang`

### ISSUE THREAD

**Issue by tyrone-anz** [prometheus/common#314]
I am trying to get rid of `github.com/gogo/protobuf` versions before v1.3.2 on my repo for [security issue](https://nvd.nist.gov/vuln/detail/CVE-2021-3121).

Due to the cyclic-dependency between `prometheus/common` and `prometheus/client_golang`, it is hard to get rid of old versions of `gogo/protobuf` as both `common`  and `client_golang` will always refer to the older version of the other.

There are just a few usages of `client_golang` here on `common` and it might be possible to remove the dependency.
- `sigv4/sigv4_test.go` - create copy of factory function `promhttp.RoundTripperFunc()`
- `version/info.go` -  create a clone of `prometheus.Collector` interface and copy function `prometheus.NewGaugeFunc()` (might be too big to copy)

As a workaround, I can use `exclude` and `replace` on my `go.mod` to force `v1.3.2` on build. But this does not work well with some IDEs and is ignored by dependency scanners. It would be great if the latest tags of the two repos would be able to remove old versions of `gogo/protobuf` in the dependency graph.

**Comment by roidelapluie** [comment]
This seems pretty much an issue with the security scanner you are using. We are using protobug 1.4.

go.sum is not a reliable source for dependencies listing.

**Comment by tyrone-anz** [comment]
Not sure how our scanner really works internally but yeah it seems to be checking `go.sum`. 

Do you have a link to protobug? Googling leads me to protobuf. Just wanted to understand how it does its scan.

So I guess removing the cyclic dependency is unlikely? Are there plans on having a stable version for Prometheus?

**Comment by beorn7** [comment]
This has been discussed before. There is no cyclic dependency on the package level (which Go prohibits). Cyclic dependencies on the Go Module level are possible and "fine". Since prometheus/common is a whole buffet of packages, all in one module, cyclic dependencies will happen all the time. The weird laddered trace-back to the beginning of history is part of the way Go Modules calculates the required version of dependencies. None of that old code will make it into the binary. Your security scanner should check what version is in the end selected by Go Modules and only notify on security issues in those versions.

**Comment by tsingsun** [comment]
any update ? in go.sum
client_golang@v1.11.0  =>(depend) common@v0.26.0 => client_golang@v1.7.1 => common@v0.10.0 => client_golang@v1.0.0 => common@v0.4.1 => client_golang@v0.9.1

with too many dependency and it is ungly

**Comment by beorn7** [comment]
As said, this is part of how Go Modules and its dependency solver is designed. While you might perceive it as "ugly", this is pretty much "working as intended", for better or worse.
