### ISSUE TITLE
Consider moving to google.golang.org/protobuf/proto

### ISSUE THREAD

**Issue by mem** [prometheus/common#317]
github.com/golang/protobuf/proto has been "deprecated" in favor of google.golang.org/protobuf/proto. For this codebase in particular this involves changing calls to `proto.MarshalTextString` to `prototext.Marshal`.

This is related to #281.

**Comment by conways-glider** [comment]
Looks like this dependency now has a security issue: https://nvd.nist.gov/vuln/detail/CVE-2021-3121

**Comment by beorn7** [comment]
My assumption so far is that the move would mean a breaking change for the users of prometheus/client_golang (which exposes a few protobuf specific parts in its interface). If we can pull it off without a breaking change, great. But if it does mean a breaking change, it has to be navigated carefully and in coordination with @kakkoyun and @bwplotka .

**Comment by bwplotka** [comment]
Ack, I think we have to do it at some point. Added ticket on our side: https://github.com/prometheus/client_golang/issues/1175

**Comment by zhsj** [comment]
Continue my comments https://github.com/prometheus/common/pull/427#issuecomment-1362478446 here, since I find it's not easy to get rid of `proto.MarshalTextString`.

proto.MarshalTextString results a string with `<,>` as delim, but `prototext.Marshal` uses `{,}` as delim. The upstream doc says the text format is not stable. Should we rely on this?

Besides, there's no decoder for `FmtProtoText`, is there any user for this format?

**Comment by beorn7** [comment]
I don't think anyone depends on the exact format of `FmtProtoText` (at least I don't think anyone should depend on it).

**Comment by SuperQ** [comment]
I fixed the issue of `proto.MarshalTextString()` by updating prometheus/client_model to `google.golang.org/protobuf/proto` first. 

This is now fixed with #479
