### ISSUE TITLE
OpenMetrics: _total suffix repeated multiple times

### ISSUE THREAD

**Issue by k-meister** [prometheus/common#605]
### Description

Today we faced the problem with counter export in openmetrics format: counter names keep being appended by "_total" suffices, one time for every new labelset.

This is how it looks in grafana metric browser after being collected by prometheus

<img width="1154" alt="Screenshot" src="https://github.com/prometheus/common/assets/11293374/4fcc1f3b-83d0-4c5f-86aa-3a05da0886c6">

### Debug

The problem seems to be around the line
https://github.com/vesari/common/blob/6a86956d41af916f0c048f4988d93994bb865b9e/expfmt/openmetrics_create.go#L255
which modifies metric name inside the loop,

and was introduced in [this commit](https://github.com/prometheus/common/pull/544/commits/6a86956d41af916f0c048f4988d93994bb865b9e).

### Affected versions

github.com/prometheus/common v0.50.0

**Comment by SuperQ** [comment]
CC @ArthurSens @vesari

**Comment by vesari** [comment]
@SuperQ I'll look into it today, thanks for pinging me

**Comment by ArthurSens** [comment]
Oh, sorry for that!

In theory, we're not changing anything by default... people should opt-in for the unit feature to see any differences. Could you share where this metric is implemented? I want to understand where we made a mistake 😬

**Comment by vesari** [comment]
@SuperQ @ArthurSens If I understood correctly, the problem was just limited to the metric name in the samples for the counters and just for the `_total` suffix. The PR that I just submitted should correct that (the case scenario should be something like test n.18). I apologize for the inconvenience.

**Comment by k-meister** [comment]
Thank you for such a quick fix! 🙏

**Comment by vesari** [comment]
You're welcome! Thanks for reporting the bug :)

**Comment by HeinKalido** [comment]
I have also encountered this problem, but had difficulty narrowing it down to this issue, because this bug report did not contain a sample of the broken metrics as text (and thus was not indexed by search engines).

Examples of the broken metrics:
```
grpc_server_handled_total_total
grpc_server_handled_total_total_total
```
or
```
promhttp_metric_handler_requests_total{code="200"} 66
promhttp_metric_handler_requests_total_total{code="500"} 0
promhttp_metric_handler_requests_total_total_total{code="503"} 0
```

To resolve it, if you can change the service being scraped, you can update `github.com/prometheus/common` past version v0.50.0
or update the prometheus scrape config with `scrape_protocols: ['PrometheusText0.0.4']`, to prevent the open metrics format from being used.
